### ISSUE TITLE
Voice Connector exception w/ logging enabled

### ISSUE THREAD

**Issue by jyjohnson** [cdklabs/cdk-amazon-chime-resources#502]
### Describe the bug

this could be just my environment, but setting 
```
     loggingConfiguration: {
          enableSIPLogs: true,
          enableMediaMetricLogs: true,
        },
```
during initial creation generates an exception: 

CREATE_FAILED        | Custom::PSTNResources | voiceConnectorvoic...omResource2AA5597F
Received response status [FAILED] from custom resource. Message returned: ForbiddenException: Access Denied for LogDestination: /aws/ChimeVoiceConnectorSipMessages

Note: if set to false and then updated to true, it works

### Expected behavior

the corresponding VC Log Group(s) should be created

### Current behavior

exception 

### Steps to Reproduce

create VC with logs enabled

### Possible Solution

 /lib/pstn/pstnCustomResources.js -- if I add 'logs:*' it works when the VC is first created

**Comment by schuettc** [comment]
https://github.com/cdklabs/cdk-amazon-chime-resources/commit/890a7431092e189ae6929cdca6940692c932f27c

Added PutResourcePolicy to fix issue with adding Logging to Voice Connector.
