### ISSUE TITLE
Unable to create any TOLLFREE ChimePhoneNumber 

### ISSUE THREAD

**Issue by joeykilpatrick** [cdklabs/cdk-amazon-chime-resources#62]
Trying to create a Toll-Free phone number like so:

```
new ChimePhoneNumber(stack, `phone-number`, {
    phoneNumberType: PhoneNumberType.TOLLFREE,
    phoneNumberTollFreePrefix: 833,
    phoneProductType: PhoneProductType.SMA,
});
```

Custom resource throws the following error:

```
Received response status [FAILED] from custom resource. Message returned: Error: {'error': "Exception thrown: {'error': 'Exception thrown: An error occurred (BadRequestException) when calling the SearchAvailablePhoneNumbers operation: Service received a bad request'}"}
```

**Comment by schuettc** [comment]
If you go in to the Chime Console, are you able to Search for a Toll Free number?  There may be a failure with requesting numbers in general related to the account.

**Comment by joeykilpatrick** [comment]
It appears there is a typo causing the issue, PR submitted. Able to provision Toll Free numbers manually and with the provided fix.
